apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: rewrite
  namespace: default
spec:
  rules:
  - host: lappy.insom.me.uk
    http:
      paths:
      - backend:
          serviceName: uchiwa
          servicePort: 3000
        path: /uchiwa/
