apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: server
  name: server
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: server
status:
  loadBalancer: {}
