apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: uchiwa
  name: uchiwa
spec:
  ports:
  - name: uchiwa
    port: 3000
    targetPort: 3000
  selector:
    service: uchiwa
status:
  loadBalancer: {}
